name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        wget 'https://dl.modular.com/public/installer/deb/ubuntu/pool/any-version/main/m/mo/modular_0.2.0/modular-0.2.0-amd64.deb' -O modular_0.2.0_amd64.deb
        sudo dpkg -i modular_0.2.0_amd64.deb
        sudo apt-get install -f
        modular clean
        modular auth ${{ secrets.MODULAR_API }}
        modular install mojo

    - name: Set MODULAR_HOME path
      run: | 
        echo "MODULAR_HOME=/home/runner/.modular" >> $GITHUB_ENV
        echo "$MODULAR_HOME/pkg/packages.modular.com_mojo/bin" >> $GITHUB_PATH
        echo "MOJO_HOME=$MODULAR_HOME/pkg/packages.modular.com_mojo/bin" >> $GITHUB_ENV

    - name: Check mojo binary
      run: |
        echo "$MOJO_HOME"
        ls $MOJO_HOME || echo "mojo binary not found"

    - name: Build
      run: |
        $MOJO_HOME/mojo package $GITHUB_WORKSPACE/src -o ${{ github.repository }}.mojopkg
#        mv ${{ github.repository }}.mojopkg ${{ github.workspace }}