name: Build and Release

# define your mojo package name here
# set the path to the directory containing the module files

env:
  PACKAGE_NAME: mojopackage.mojopkg
  MOJO_DIR: src
  MOJO_HOME: /home/runner/.modular/pkg/packages.modular.com_mojo/bin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        wget -q 'https://dl.modular.com/public/installer/deb/ubuntu/pool/any-version/main/m/mo/modular_0.2.0/modular-0.2.0-amd64.deb' -O modular_0.2.0_amd64.deb
        sudo dpkg -i modular_0.2.0_amd64.deb
        sudo apt-get install -f
        modular clean
        modular auth ${{ secrets.MODULAR_API }}
        modular install mojo

    - name: Build
      run: |
        ${{ env.MOJO_HOME }}/mojo package ./${{ env.MOJO_DIR }} -o ${{ github.workspace }}/${{ env.PACKAGE_NAME }}

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ github.workspace }}/${{ env.PACKAGE_NAME }}